version: '3.9'

services:
  go-app:
    container_name: go-app
    image: go-api
    build: 
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "8000:8000"
      - "2345:2345"
    security_opt:
      - "seccomp:unconfined"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata: {} 